version: '3.8'

services:
  capabilities:
    build:
      context: ./coachartie_capabilities
      args:
        - NODE_ENV=${NODE_ENV:-production}
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./.env:/app/.env:ro
    ports:
      - "9991:9991"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9991/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  discord:
    build:
      context: ./coachartie_discord
      args:
        - NODE_ENV=${NODE_ENV:-production}
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      capabilities:
        condition: service_healthy

  sms:
    build:
      context: ./coachartie_sms
      args:
        - NODE_ENV=${NODE_ENV:-production}
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=3000
    ports:
      - "9993:3000"
    depends_on:
      capabilities:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  email:
    build:
      context: ./coachartie_email
      args:
        - NODE_ENV=${NODE_ENV:-production}
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=3000
    ports:
      - "9994:3000"
    depends_on:
      capabilities:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  brain:
    build:
      context: ./coachartie_brain
      args:
        - NODE_ENV=${NODE_ENV:-production}
    restart: unless-stopped
    env_file: .env
    environment:
      - NITRO_PORT=3000
      - NITRO_HOST=0.0.0.0
    ports:
      - "9992:3000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"