version: '3.8'

services:
  capabilities:
    build:
      context: ./coachartie_capabilities
      args:
        - NODE_ENV=${NODE_ENV:-production}
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./.env:/app/.env:ro
    ports:
      - "9991:9991"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9991/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  discord:
    build:
      context: ./coachartie_discord
      args:
        - NODE_ENV=${NODE_ENV:-production}
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      capabilities:
        condition: service_healthy